- name: Copy logstash yum repo file
  copy:
    src=logstash.repo
    dest=/etc/yum.repos.d/logstash.repo
    owner=root
    group=root
    mode=0644

- name: Install logstash
  yum:
    name: logstash
    state: present

- name: Copy logstash filter configuration
  template:
    src=logstash.conf.j2
    dest=/etc/logstash/conf.d/logstash.conf
    owner=logstash
    group=logstash
    mode=0644

- name: Start or restart logstash service
  command: systemctl restart logstash.service

- name: Setup logstash service to autostart
  service: name=logstash state=started enabled=true

